### ISSUE TITLE
Webpack compilation error after update

### ISSUE THREAD

**Issue by PavelDemyanenko** [mswjs/headers-polyfill#45]
Hello,

I believe that after update to v3.1.0 there're some troubles with compiling. Failed to compile output looks like this:
```
../node_modules/msw/lib/index.js
Module not found: Package path ./lib is not exported from package /app/node_modules/headers-polyfill (see exports field in /app/node_modules/headers-polyfill/package.json)
Import trace for requested module:
./src/mocks/browser.js
./src/mocks/index.js
./src/pages/executions-tmv1/index.page.tsx
> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Uploading artifacts for failed job
```
Didn't have much time to deep dive, but maybe you're aware?

**Comment by kettanaito** [comment]
Hey, @PavelDemyanenko. 

Looks like you're consuming `headers-polyfill` indirectly, through MSW. Please update the `msw` package to have the fix there.

**Comment by PavelDemyanenko** [comment]
Hey,  @kettanaito much thanks for quick response. My bad I haven't looked in closed issues. I see that there are already plenty of same questions. I'll try your suggestion.

**Comment by snaka** [comment]
We have confirmed that this issue has been resolved with the release of the following PR. 👍 
https://github.com/mswjs/msw/pull/1407

**Comment by kettanaito** [comment]
No worries.
